### PR TITLE
ORC-1767: [C++] Improve writing performance of encoded string column and support EncodedStringVectorBatch for StringColumnWriter

### PR DESCRIPTION
**Pull request by taiyang-li**
### What changes were proposed in this pull request?

ORC-1767: [C++] Improve writing performance of encoded string column and support EncodedStringVectorBatch for StringColumnWriter

Chery pick commit in apache/orc main branch: https://github.com/apache/orc/commit/97a37972eba0bfecf3cd31f6de23216159814129

### CODE REVIEW

**Comment by taiyang-li** [comment]
@alexey-milovidov can you help review it ? Thanks!

**Comment by nickitat** [comment]
i don't think cherry-picking is the right approach. we're better to maintain `main` branch in the state when it contains some prefix of upstream commits with our own patches on top.
in other words let's update the `main` to the current upstream HEAD

**Comment by taiyang-li** [comment]
I tried, but there are so many conflicts after rebase ClickHouse main branch on apache main branch. I'm curious how it is done before?  If we want to sync from upstream, which is preferred, `git merge` or `git rebase` ?   I tried both ways but they all doesn't work. Hope for you suggestions, thanks!

**Comment by nickitat** [comment]
> I tried, but there are so many conflicts after rebase ClickHouse main branch on apache main branch. I'm curious how it is done before? If we want to sync from upstream, which is preferred, `git merge` or `git rebase` ? I tried both ways but they all doesn't work. Hope for you suggestions, thanks!

i made an attempt here: https://github.com/ClickHouse/ClickHouse/pull/69473

**Comment by taiyang-li** [comment]
@nickitat  Thanks, but I'm afraid your example doesn't really solve the problems I met. It need to solve so many conflicts if you want to sync ClickHouse/orc with upstream apache/orc.

**Comment by nickitat** [comment]
> @nickitat Thanks, but I'm afraid your example doesn't really solve the problems I met. It need to solve so many conflicts if you want to sync ClickHouse/orc with upstream apache/orc.

contrib reset to a new commit that is upstream/main plus one our commit (two other no longer needed).
CH builds with it successfully. we only need to fix tests.
so what are those `so many conflicts` you're talking about?

**Comment by taiyang-li** [comment]
> > @nickitat Thanks, but I'm afraid your example doesn't really solve the problems I met. It need to solve so many conflicts if you want to sync ClickHouse/orc with upstream apache/orc.
> 
> contrib reset to a new commit that is upstream/main plus one our commit (two other no longer needed). CH builds with it successfully. we only need to fix tests. so what are those `so many conflicts` you're talking about?

It will cause a lot of conflicts. Fixing them is nearly impossible. 
```
git checkout ClickHouse/main
git rebase apache/main 
```
 
Cherry pick is a good idea if there are not too many commits of our own. BTW, which commits that are not contributed to upstream need to be cherry picked ?

**Comment by nickitat** [comment]
> > > @nickitat Thanks, but I'm afraid your example doesn't really solve the problems I met. It need to solve so many conflicts if you want to sync ClickHouse/orc with upstream apache/orc.
> > 
> > 
> > contrib reset to a new commit that is upstream/main plus one our commit (two other no longer needed). CH builds with it successfully. we only need to fix tests. so what are those `so many conflicts` you're talking about?
> 
> It will cause a lot of conflicts. Fixing them is nearly impossible.
> 
> ```
> git checkout ClickHouse/main
> git rebase apache/main 
> ```
> 
> Cherry pick is a good idea if there are not too many commits of our own. BTW, which commits that are not contributed to upstream need to be cherry picked ?

what i'm saying is that i did this exercise yesterday. the only conflicting files were `c++/src/Options.hh`, `c++/src/sargs/ExpressionTree.cc`, `c++/src/sargs/PredicateLeaf.cc` afair. 

you may see [here](https://github.com/ClickHouse/orc/pull/17) that from our own commits only one (yours) was preserved after rebase. the other two contained upstreamed fixes.

Screenshot 2024-09-11 at 13 37 39

so i don't think we have any problems with the conflicts. only with tests

**Comment by taiyang-li** [comment]
@nickitat will you merge https://github.com/ClickHouse/orc/pull/17 ?  If the answer if yes, I'll close current PR. All I need is the  newest commits from upstream.

**Comment by nickitat** [comment]
> @nickitat will you merge #17 ? If the answer if yes, I'll close current PR. All I need is the newest commits from upstream.

yes, i just need to find some time to figure out test failures.

**Comment by taiyang-li** [comment]
duplicated with https://github.com/ClickHouse/orc/pull/17

**Pull request closed without merging**
