### PR TITLE
Improve some interfaces about ORC filter push down

### PR DESCRIPTION
**Pull request by taiyang-li**
### What changes were proposed in this pull request?
Improve some interfaces about orc search argument and fix one bug about invalid memory access.

### CODE REVIEW

**Comment by al13n321** [comment]
Diverging the fork from the upstream for something this minor doesn't seem worth it. Can you try to either get these changes accepted into the upstream `apache/orc` or try to do without them?

Seems that this should be pretty upstreamable, especially with some changes to keep full compatibility (if needed):
 * Can keep both overloads of `searchArgument()`, with the `unique_ptr` overload just creating a `shared_ptr` and calling the `shared_ptr` overload.
 * Can keep both versions of `getChild()`, naming the new one `getChildRef()` or something.

**Review by al13n321 — APPROVED** [review]
Ok, people told me this is fine and we actually commit to these forks freely.

**Comment by taiyang-li** [comment]
@al13n321  failed java not related to this PR. And I don't know why c++ tests on windows failed, but let's try to fix it.

**Comment by taiyang-li** [comment]
> @al13n321 failed java not related to this PR. And I don't know why c++ tests on windows failed, but let's try to fix it.

done

**Comment by taiyang-li** [comment]
@al13n321 can we merge this pr first if it is ok ?

**Pull request merged**
